name: asd1xx-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: php
        uses: shivammathur/setup-php@v2 
        with:
          php-version: '8.3'

      - name: composer
        run: composer install

      - name: validate
        run: composer validate

      - name: linter
        run: make lint
      
      - name: Run test & publish code coverage
        uses: paambaati/codeclimate-action@v5
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage
          coverageLocations: build/logs/clover.xml:clover
          debug: true